routes/web.php
<?php

use Illuminate\Support\Facades\Route;


// Home
Route::get("/", "HomeController@index")->name("index");
Route::get("/sop", "HomeController@sop")->name("sop");
Route::post("/sop", "HomeController@postSop")->name("post.sop");

// Home
Route::prefix("/home")->name("home.")->group(function (){
    Route::get("/dashboard","HomeController@dashboard")->name("dashboard")->middleware("mustLogin");
});

// admin
Route::prefix("/admin")->name("admin.")->group(function (){
    Route::get("/dashboard", "AdminController@dashboard")->name("dashboard");
    Route::get("/pemesanan", "AdminController@pemesanan")->name("pemesanan");
    Route::get("/tiket", "AdminController@tiket")->name("tiket");
    Route::get("/pendaki", "AdminController@pendaki")->name("pendaki");
    Route::get("/user", "AdminController@user")->name("user");
});

// Pemesanan Router
Route::prefix("/pemesanan")->name("pemesanan.")->group(function (){
    Route::get("/tambah", "PemesananController@tambah")->name("tambah");
    Route::post("/tambah","PemesananController@postTambah")->name("post.tambah");
    Route::get("/cetak-pdf/{pemesananId}", "PemesananController@cetakPdf")->name("cetakPdf");
    Route::get("/hapus/{pemesanan_pendaki}", "PemesananController@hapus")->name("hapus");
    Route::get("/riwayat", "PemesananController@riwayat")->name("riwayat");
    Route::get("/bayar/{id}", "PemesananController@bayar")->name("bayar")->middleware("mustLogin");
    Route::post("/bayar", "PemesananController@postBayar")->name("post.bayar")->middleware("mustLogin");
});

// User Router
Route::prefix("/user")->name("user.")->group(function (){
    Route::get("/login", "UserController@login")->name("login")->middleware("mustNotLogin");
    Route::post("/login", "UserController@postLogin")->name("post.login");
    Route::get("/registrasi/{pemesananId}", "UserController@formRegistrasi")->name("registrai");
    Route::post("/registrasi/{pemesananId}", "UserController@postRegistrasi")->name("post.registrasi");
    Route::get("/logout", "UserController@logout")->name("logout");
    Route::post("/add-admin", "UserController@addAdmin")->name("add.admin");
    Route::get("/register-account", "UserController@registerAccount")->name("register-account");
    Route::post("/register-account", "UserController@postRegisterAccount")->name("post.register-account");
});

// Pendaki Route
Route::prefix("/pendaki")->name("pendaki.")->group(function (){
    Route::post("/cek-nik", "PendakiController@cekNik")->name("cekNik");
    Route::get("/tambah-anggota/{pemesananId}", "PendakiController@tambahAnggota")->name("tambah.anggota");
    Route::post("/tambah-anggota/{pemesananId}", "PendakiController@postTambahAnggota")->name("post.tambah.anggota");
});

// Tiket
Route::prefix("/tiket")->name("tiket.")->group(function (){
    Route::post("/add", "TiketController@add")->name("add");
    Route::get("/delete/{id}", "TiketController@delete")->name("delete");
});

resources/views/admin/bayar.blade.php
@extends("template.template-admin")

@section("content")


{{--    @foreach($pemesanan as $ps)--}}
<div class="row g-4 mb-4">
    <div class="col-12 col-lg-8">
        <div class="app-card app-card-basic d-flex flex-column align-items-start shadow-sm">
            <div class="app-card-header p-3 border-bottom-0">
                <div class="row align-items-center gx-3">
                    <div class="col-auto">
                        <div class="app-icon-holder">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-receipt" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M1.92.506a.5.5 0 0 1 .434.14L3 1.293l.646-.647a.5.5 0 0 1 .708 0L5 1.293l.646-.647a.5.5 0 0 1 .708 0L7 1.293l.646-.647a.5.5 0 0 1 .708 0L9 1.293l.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .801.13l.5 1A.5.5 0 0 1 15 2v12a.5.5 0 0 1-.053.224l-.5 1a.5.5 0 0 1-.8.13L13 14.707l-.646.647a.5.5 0 0 1-.708 0L11 14.707l-.646.647a.5.5 0 0 1-.708 0L9 14.707l-.646.647a.5.5 0 0 1-.708 0L7 14.707l-.646.647a.5.5 0 0 1-.708 0L5 14.707l-.646.647a.5.5 0 0 1-.708 0L3 14.707l-.646.647a.5.5 0 0 1-.801-.13l-.5-1A.5.5 0 0 1 1 14V2a.5.5 0 0 1 .053-.224l.5-1a.5.5 0 0 1 .367-.27zm.217 1.338L2 2.118v11.764l.137.274.51-.51a.5.5 0 0 1 .707 0l.646.647.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.509.509.137-.274V2.118l-.137-.274-.51.51a.5.5 0 0 1-.707 0L12 1.707l-.646.647a.5.5 0 0 1-.708 0L10 1.707l-.646.647a.5.5 0 0 1-.708 0L8 1.707l-.646.647a.5.5 0 0 1-.708 0L6 1.707l-.646.647a.5.5 0 0 1-.708 0L4 1.707l-.646.647a.5.5 0 0 1-.708 0l-.509-.51z"/>
                                <path fill-rule="evenodd" d="M3 4.5a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm8-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5z"/>
                            </svg>
                        </div><!--//icon-holder-->

                    </div><!--//col-->
                    <div class="col-auto">
                        <h4 class="app-card-title">{{ $pemesanan->tiket->label }}</h4>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//app-card-header-->
            <div class="app-card-body px-4">
                <div class="row">
                    <div class="qr-code text-center">
                        <img src="{{ asset("storage/" . $pemesanan->qr_code) }}" class="img-fluid" >
                    </div>
                </div>

                <div class="container mt-2">
                    <div class="row">
                        <div class="col-8 mx-auto">
                            <table class="table">
                                <tr>
                                    <td><b>ID Kelompok</b></td>
                                    <td><b>:</b></td>
                                    <td class="text-uppercase"><b>{{ $pemesanan->id }}</b></td>
                                </tr>
                                <tr>
                                    <td><b>Tanggal Berangkat</b></td>
                                    <td><b>:</b></td>
                                    <td class="text-uppercase"><b>{{ $pemesanan->tanggal_berangkat }}</b></td>
                                </tr>
                                <tr>
                                    <td><b>Tanggal Pulang</b></td>
                                    <td><b>:</b></td>
                                    <td class="text-uppercase"><b>{{ $pemesanan->tanggal_pulang }}</b></td>
                                </tr>
                                <tr>
                                    <td><b>Anggota</b></td>
                                    <td><b>:</b></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-8 mx-auto">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Nama</th>
                                    <th scope="col">Alamat</th>
                                    <th scope="col">Nomer Hp</th>
                                    <th scope="col">Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($pemesanan->pendaki as $pendaki)
                                    <tr>
                                        <th scope="row"></th>
                                        <th>{{ $pendaki->nama }}</th>
                                        <td>{{ $pendaki->alamat }}</td>
                                        <td>{{ $pendaki->nomer_hp }}</td>
                                        <td class="text-uppercase">{{ $pendaki->pivot->status_pendaki }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="5">
                                            <b>Total Pembayaran Tiket : Rp. {{ count($pemesanan->pendaki) * $pemesanan->tiket->harga }}</b>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            <div class="app-card-footer p-4 mt-auto">
                <form method="post" action="{{ route("pemesanan.post.bayar") }}">
                    @Csrf
                    <input type="hidden" name="id_pemesanan" value="{{ $pemesanan->id }}">
                    @if($pemesanan->status_pembayaran == "BELUM_BAYAR")
                        <button class="btn app-btn-primary" type="submit">Terbayar</button>
                    @else
                        <button class="btn app-btn-secondary disabled" type="button">Sudah dibayar</button
                    @endif

                </form>
            </div><!--//app-car
    d-footer-->
        </div><!--//app-card-->
    </div><!--//col-->
</div><!--//row-->
{{--    @endforeach--}}
@endsection

{{--@endsection--}}

resources/views/admin/dashboard.blade.php
@extends("template.template-admin")

@section("content")
<div class="app-card alert alert-dismissible shadow-sm mb-4 border-left-decoration" role="alert">
    <div class="inner">
        <div class="app-card-body p-3 p-lg-4">
            <h3 class="mb-3">Selamat Datang</h3>
            <div class="row gx-5 gy-3">
                <div class="col-12 col-lg-9">

                    <div>Anda Login sebagai admin </div>
                </div><!--//col-->
            </div><!--//row-->
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div><!--//app-card-body-->

    </div><!--//inner-->
</div><!--//app-card-->

<div class="row g-4 mb-4">
    <div class="col-6 col-lg-3">
        <div class="app-card app-card-stat shadow-sm h-100">
            <div class="app-card-body p-3 p-lg-4">
                <h4 class="stats-type mb-1">Total Pemesanan</h4>
                <div class="stats-figure">{{ $totalPemesanan }}</div>

            </div><!--//app-card-body-->
            <a class="app-card-link-mask" href="#"></a>
        </div><!--//app-card-->
    </div><!--//col-->

    <div class="col-6 col-lg-3">
        <div class="app-card app-card-stat shadow-sm h-100">
            <div class="app-card-body p-3 p-lg-4">
                <h4 class="stats-type mb-1">Total User</h4>
                <div class="stats-figure">{{ $totalUser }}</div>
            </div><!--//app-card-body-->
            <a class="app-card-link-mask" href="#"></a>
        </div><!--//app-card-->
    </div><!--//col-->
    <div class="col-6 col-lg-3">
        <div class="app-card app-card-stat shadow-sm h-100">
            <div class="app-card-body p-3 p-lg-4">
                <h4 class="stats-type mb-1">Total Tiket</h4>
                <div class="stats-figure">{{ $totalTiket }}</div>
                <div class="stats-meta">
                    Open</div>
            </div><!--//app-card-body-->
            <a class="app-card-link-mask" href="#"></a>
        </div><!--//app-card-->
    </div><!--//col-->
    <div class="col-6 col-lg-3">
        <div class="app-card app-card-stat shadow-sm h-100">
            <div class="app-card-body p-3 p-lg-4">
                <h4 class="stats-type mb-1">Pemesanan Terbaru</h4>
                <div class="stats-figure">{{ $totalPemesananBaru }}</div>
                <div class="stats-meta">New</div>
            </div><!--//app-card-body-->
            <a class="app-card-link-mask" href="#"></a>
        </div><!--//app-card-->
    </div><!--//col-->
</div><!--//row-->

@endsection

resources/views/admin/pemesanan.blade.php
@extends("template.template-admin")

@section("content")
    <div class="tab-content" id="orders-table-tab-content">
        <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
            <div class="app-card app-card-orders-table shadow-sm mb-5">
                <div class="app-card-body">
                    <div class="table-responsive">
                        <table class="table app-table-hover mb-0 text-left">
                            <thead>
                            <tr>
                                <th class="cell">ID</th>
                                <th class="cell">Status</th>
                                <th class="cell">Tiket</th>
                                <th class="cell">Tanggal Pemesanan</th>
                                <th class="cell">Tanggal Berangkat</th>
                                <th class="cell">Tanggal Pulang</th>
                                <th class="cell"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($pemesanan as $ps)
                            <tr>
                                <td class="cell">#{{ $ps->id }}</td>
                                @if($ps->status_pembayaran == "TERBAYAR")
                                    <td class="cell"><span class="badge bg-success">Terbayar</span></td>
                                @else
                                    <td class="cell"><span class="badge bg-danger">Belum Terbayar</span></td>
                                @endif
                                <td class="cell">{{ $ps->tiket->label }}</td>
                                <td class="cell"><span>{{ $ps->created_at }}</span></td>
                                <td class="cell"><span>{{ $ps->tanggal_berangkat }}</span></td>
                                <td class="cell"><span>{{ $ps->tanggal_pulang}}</span></td>
                                @if($ps->status_pembayaran == "TERBAYAR")
                                    <td class="cell"><a class="btn-sm app-btn-secondary" href="{{ route("pemesanan.bayar", ["id" => $ps->id]) }}">View</a></td>
                                @else
                                    <td class="cell"><a class="btn-sm app-btn-primary" href="{{ route("pemesanan.bayar", ["id" => $ps->id]) }}">Bayar</a></td>
                                @endif
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div><!--//table-responsive-->

                </div><!--//app-card-body-->
            </div><!--//app-card-->
            {{ $pemesanan->links() }}


        </div><!--//tab-pane-->

@endsection

resources/views/admin/pendaki.blade.php
@extends("template.template-admin")

@section("content")
    <div class="tab-content" id="orders-table-tab-content">
        <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
            <div class="app-card app-card-orders-table shadow-sm mb-5">
                <div class="app-card-body">
                    <div class="table-responsive">
                        <table class="table app-table-hover mb-0 text-left">
                            <thead>
                            <tr>
                                <th class="cell">ID</th>
                                <th class="cell">NIK</th>
                                <th class="cell">Nama</th>
                                <th class="cell">Alamat</th>
                                <th class="cell">No Hp</th>
                                <th class="cell">Jenis Kelamin</th>
                                <th class="cell">Tanggal Lahir</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($pendaki as $pd)
                                <tr>
                                    <td class="cell">#{{ $pd->id }}</td>
                                    <td class="cell">{{ $pd->nik }}</td>
                                    <td class="cell">{{ $pd->nama }}</td>
                                    <td class="cell">{{ $pd->alamat }}</td>
                                    <td class="cell">{{ $pd->nomer_hp }}</td>
                                    <td class="cell">{{ $pd->jenis_kelamin }}</td>
                                    <td class="cell">{{ $pd->tanggal_lahir }}</td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div><!--//table-responsive-->
                </div><!--//app-card-body-->

            </div><!--//app-card-->

            {{ $pendaki->links() }}


        </div><!--//tab-pane-->

@endsection

resources/views/admin/tiket.blade.php
@extends("template.template-admin")

@section("content")
@if (session('status'))
<div class="alert alert-success">
    {{ session('status') }}
</div>
@endif
<button class="btn app-btn-primary mb-4" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
Tambah Tiket
</button>
<div class="tab-content" id="orders-table-tab-content">
<div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
    <div class="app-card app-card-orders-table shadow-sm mb-5">
        <div class="app-card-body">
            <div class="table-responsive">
                <table class="table app-table-hover mb-0 text-left">
                    <thead>
                    <tr>
                        <th class="cell">Tiket</th>
                        <th class="cell">Harga</th>
                        <th class="cell">action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tiket as $tk)
                        <tr>
                            <td class="cell">{{ $tk->label }}</td>
                            <td class="cell">Rp. {{ $tk->harga }}</td>
                            <td class="cell">
                                <a href="{{ route("tiket.delete", ["id" => $tk->id]) }}" class="btn btn-sm btn-danger">Hapus</a>
                                <a href="#" class="btn btn-sm btn-info">Edit</a>
                            </td>
                      </tr>
                    @endforeach
                    </tbody>
                </table>
            </div><!--//table-responsive-->

        </div><!--//app-card-body-->
    </div><!--//app-card-->


</div><!--//tab-pane-->

<form method="post" action="{{ route("tiket.add") }}">
    @Csrf
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Label</label>
                        <input type="text" name="label" class="form-control" id="setting-input-1" placeholder="ex: Tiket Pendakian" value="{{ old("label") }}">
                    </div>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Harga</label>
                        <input type="number" name="harga" class="form-control" id="setting-input-1" placeholder="Harga" value="{{ old("harga") }}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn app-btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn app-btn-primary">Tambah</button>
                </div>
            </div>
        </div>
    </div>
</form>

@endsection

resources/views/admin/user.blade.php
@extends("template.template-admin")

@section("content")
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif
<div class="app-card alert alert-dismissible shadow-sm mb-4 border-left-decoration" role="alert">
    <div class="inner">
        <div class="app-card-body p-3 p-lg-4">
            <div class="row gx-5 gy-3">
                <div class="col-12 col-lg-9">
                    <button class="btn app-btn-primary mb-4" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                        Tambah User Admin
                    </button>
                    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                        <li class="nav-item" role="presentation">
                            <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Admin</button>
                        </li>
                        <li class="nav-item" role="presentation">
                            <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">User</button>
                        </li>
                    </ul>
                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#ID</th>
                                    <th scope="col">Username</th>
                                    <th scope="col">Role</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($admin as $ad)
                                    <tr>
                                        <td class="cell">#{{ $ad->id }}</td>
                                        <td class="cell">{{ $ad->username }}</td>
                                        <td class="cell">{{ $ad->role }}</td>

                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">#ID</th>
                                    <th scope="col">Username</th>
                                    <th scope="col">Role</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($user as $usr)
                                    <tr>
                                        <td class="cell">#{{ $usr->id }}</td>
                                        <td class="cell">{{ $usr->username }}</td>
                                        <td class="cell">{{ $usr->role }}</td>

                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                            {{ $user->links() }}
                        </div>
                    </div>
                </div><!--//col-->
            </div><!--//row-->
        </div><!--//app-card-body-->

    </div><!--//inner-->
</div><!--//app-card-->

<!-- Modal -->
<form method="post" action="{{ route("user.add.admin") }}">
    @Csrf
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Nama</label>
                        <input type="text" name="nama" class="form-control" id="setting-input-1" placeholder="Nama" value="{{ old("nama") }}">
                    </div>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Email</label>
                        <input type="text" name="email" class="form-control" id="setting-input-1" placeholder="Email" value="{{ old("email") }}">
                    </div>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Nomer HP</label>
                        <input type="text" name="nomer_hp" class="form-control" id="setting-input-1" placeholder="Nomer Hp" value="{{ old("nomer_hp") }}">
                    </div>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Username</label>
                        <input type="text" name="username" class="form-control" id="setting-input-1" placeholder="Username" value="{{ old("username") }}">
                    </div>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Password</label>
                        <input type="password" name="password" class="form-control" id="setting-input-1" placeholder="Password">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn app-btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn app-btn-primary">Tambah</button>
                </div>
            </div>
        </div>
    </div>
</form>




@endsection