routes/web.php
<?php

use Illuminate\Support\Facades\Route;


// Home
Route::get("/", "HomeController@index")->name("index");
Route::get("/sop", "HomeController@sop")->name("sop");
Route::post("/sop", "HomeController@postSop")->name("post.sop");

// Home
Route::prefix("/home")->name("home.")->group(function (){
    Route::get("/dashboard","HomeController@dashboard")->name("dashboard")->middleware("mustLogin");
});

// admin
Route::prefix("/admin")->name("admin.")->group(function (){
    Route::get("/dashboard", "AdminController@dashboard")->name("dashboard");
    Route::get("/pemesanan", "AdminController@pemesanan")->name("pemesanan");
    Route::get("/tiket", "AdminController@tiket")->name("tiket");
    Route::get("/pendaki", "AdminController@pendaki")->name("pendaki");
    Route::get("/user", "AdminController@user")->name("user");
});

// Pemesanan Router
Route::prefix("/pemesanan")->name("pemesanan.")->group(function (){
    Route::get("/tambah", "PemesananController@tambah")->name("tambah");
    Route::post("/tambah","PemesananController@postTambah")->name("post.tambah");
    Route::get("/cetak-pdf/{pemesananId}", "PemesananController@cetakPdf")->name("cetakPdf");
    Route::get("/hapus/{pemesanan_pendaki}", "PemesananController@hapus")->name("hapus");
    Route::get("/riwayat", "PemesananController@riwayat")->name("riwayat");
    Route::get("/bayar/{id}", "PemesananController@bayar")->name("bayar")->middleware("mustLogin");
    Route::post("/bayar", "PemesananController@postBayar")->name("post.bayar")->middleware("mustLogin");
});

// User Router
Route::prefix("/user")->name("user.")->group(function (){
    Route::get("/login", "UserController@login")->name("login")->middleware("mustNotLogin");
    Route::post("/login", "UserController@postLogin")->name("post.login");
    Route::get("/registrasi/{pemesananId}", "UserController@formRegistrasi")->name("registrai");
    Route::post("/registrasi/{pemesananId}", "UserController@postRegistrasi")->name("post.registrasi");
    Route::get("/logout", "UserController@logout")->name("logout");
    Route::post("/add-admin", "UserController@addAdmin")->name("add.admin");
    Route::get("/register-account", "UserController@registerAccount")->name("register-account");
    Route::post("/register-account", "UserController@postRegisterAccount")->name("post.register-account");
});

// Pendaki Route
Route::prefix("/pendaki")->name("pendaki.")->group(function (){
    Route::post("/cek-nik", "PendakiController@cekNik")->name("cekNik");
    Route::get("/tambah-anggota/{pemesananId}", "PendakiController@tambahAnggota")->name("tambah.anggota");
    Route::post("/tambah-anggota/{pemesananId}", "PendakiController@postTambahAnggota")->name("post.tambah.anggota");
});

// Tiket
Route::prefix("/tiket")->name("tiket.")->group(function (){
    Route::post("/add", "TiketController@add")->name("add");
    Route::get("/delete/{id}", "TiketController@delete")->name("delete");
});

app/Http/Controllers/PemesananController.php
<?php

namespace App\Http\Controllers;

use App\Exceptions\PemesananNotFoundException;
use App\Http\Requests\BayarPemesananRequest;
use App\Http\Requests\PemesananTiketRequest;
use App\Model\Pemesanan;
use App\Model\Tiket;
use App\Service\Impl\PemesananServiceImpl;
use App\Service\Impl\SessionServiceImpl;
use App\Service\PemesananService;
use App\Service\SessionService;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;

class PemesananController extends Controller
{
    private PemesananService $pemesananService;
    private SessionService $sessionService;

    //
    public function __construct()
    {
        $this->pemesananService = new PemesananServiceImpl();
        $this->sessionService = new SessionServiceImpl();
    }

    public function tambah()
    {
        $tikets = Tiket::all();
        return view("pemesanan.tiket", [
            "title" => "Pemesanan Tiket",
            "tikets" => $tikets
        ]);
    }

    public function postTambah(PemesananTiketRequest $request)
    {
        $response = $this->pemesananService->tambah($request);
        return redirect("/user/registrasi/" . $response->pemesanan->id);
    }

    public function cetakPdf($pemesananId)
    {
        $pendaki = $this->sessionService->current();
        $pemesanan = $pendaki->pemesanan()->where("status_pendaki", "ketua")->get();

        return view("pemesanan.cetak-pdf", [
            "pemesanan" => $pemesanan
        ]);
    }

    public function hapus(string $id){
        DB::table("pemesanan_pendaki")->delete($id);

        return back();
    }

    public function riwayat()
    {
        $pendaki = $this->sessionService->current();

        $pemesanan = $pendaki->pemesanan()->get();

        return view("pemesanan.riwayat", [
            "title" => "Riwayat Pemesanan",
            "pemesanan" => $pemesanan
        ]);
    }

    public function bayar(string $id)
    {

        $pemesanan = Pemesanan::find($id);

        return view("admin.bayar", [
            "title" => "Bayar Pemesanan",
            "pemesanan" => $pemesanan
        ]);
    }

    public function postBayar(BayarPemesananRequest $request){
        try {
            $this->pemesananService->bayar($request);
            return redirect()->route("pemesanan.bayar", ["id" => $request->id_pemesanan]);
        }catch (PemesananNotFoundException $exception){
            return redirect()->route("pemesanan.bayar")->with("error", $exception->getMessage());
        }
    }


}

resources/views/pemesanan/cetak-pdf.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script defer src="{{ asset('/assets/plugins/fontawesome/js/all.min.js') }}"></script>

    <!-- App CSS -->
    <link id="theme-style" rel="stylesheet" href="{{ asset('/assets/css/portal.css') }}">


    <title>Bukti Pendaftaran</title>
    <!-- Fonts -->
    <style>
    </style>
</head>
<body>
    <div class="logo text-center">
        <img src="{{ asset("assets/images/logo.png") }}">
    </div>
    @foreach($pemesanan as $ps)
    <div class="row">
        <div class="tiket text-center">
            <h4>{{ $ps->tiket->label }}</h4>
        </div>
        <div class="qr-code text-center">
            <img src="{{ asset("storage/" . $ps->qr_code) }}" class="img-fluid" >
        </div>
    </div>

    <div class="container mt-2">
        <div class="row">
            <div class="col-8 mx-auto">
                <table class="table">
                    <tr>
                        <td><b>ID Kelompok</b></td>
                        <td><b>:</b></td>
                        <td class="text-uppercase"><b>{{ $ps->id }}</b></td>
                    </tr>
                    <tr>
                        <td><b>Tanggal Berangkat</b></td>
                        <td><b>:</b></td>
                        <td class="text-uppercase"><b>{{ $ps->tanggal_berangkat }}</b></td>
                    </tr>
                    <tr>
                        <td><b>Tanggal Pulang</b></td>
                        <td><b>:</b></td>
                        <td class="text-uppercase"><b>{{ $ps->tanggal_pulang }}</b></td>
                    </tr>
                    <tr>
                        <td><b>Anggota</b></td>
                        <td><b>:</b></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-8 mx-auto">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Alamat</th>
                        <th scope="col">Nomer Hp</th>
                        <th scope="col">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($ps->pendaki as $pendaki)
                    <tr>
                        <th scope="row"></th>
                        <th>{{ $pendaki->nama }}</th>
                        <td>{{ $pendaki->alamat }}</td>
                        <td>{{ $pendaki->nomer_hp }}</td>
                        <td class="text-uppercase">{{ $pendaki->pivot->status_pendaki }}</td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <b>Total Pembayaran Tiket : Rp. {{ count($ps->pendaki) * $ps->tiket->harga }}</b>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="container mt-2 px-5">
        <div class="row">
            <div class="col-12">
                <h3>Catatan</h3>
                <ul>
                    <li>Bukti pendaftaran harap dibawa</li>
                    <li>Membawa fotocopy kartu identitas ketua kelompok</li>
                    <li>Harap membawa uang sebesar <b>Rp . {{ count($ps->pendaki) * $ps->tiket->harga }}</b> untuk pembayaran tiket</li>
                </ul>
            </div>
        </div>
    </div>
    @endforeach

    <!-- Javascript -->
    <script src="{{asset('/assets/plugins/popper.min.js')}}"></script>
    <script src="{{asset('/assets/plugins/bootstrap/js/bootstrap.min.js')}}"></script>

    <!-- Page Specific JS -->
    <script src="{{asset('/assets/js/app.js')}}"></script>
</body>
</html>

resources/views/pemesanan/riwayat.blade.php
@extends("template.template-user")

@section("content")

    @foreach($pemesanan as $ps)
        <div class="row g-4 mb-4">
            <div class="col-12 col-lg-8">
                <div class="app-card app-card-basic d-flex flex-column align-items-start shadow-sm">
                    <div class="app-card-header p-3 border-bottom-0">
                        <div class="row align-items-center gx-3">
                            <div class="col-auto">
                                <div class="app-icon-holder">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-receipt" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M1.92.506a.5.5 0 0 1 .434.14L3 1.293l.646-.647a.5.5 0 0 1 .708 0L5 1.293l.646-.647a.5.5 0 0 1 .708 0L7 1.293l.646-.647a.5.5 0 0 1 .708 0L9 1.293l.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .801.13l.5 1A.5.5 0 0 1 15 2v12a.5.5 0 0 1-.053.224l-.5 1a.5.5 0 0 1-.8.13L13 14.707l-.646.647a.5.5 0 0 1-.708 0L11 14.707l-.646.647a.5.5 0 0 1-.708 0L9 14.707l-.646.647a.5.5 0 0 1-.708 0L7 14.707l-.646.647a.5.5 0 0 1-.708 0L5 14.707l-.646.647a.5.5 0 0 1-.708 0L3 14.707l-.646.647a.5.5 0 0 1-.801-.13l-.5-1A.5.5 0 0 1 1 14V2a.5.5 0 0 1 .053-.224l.5-1a.5.5 0 0 1 .367-.27zm.217 1.338L2 2.118v11.764l.137.274.51-.51a.5.5 0 0 1 .707 0l.646.647.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.509.509.137-.274V2.118l-.137-.274-.51.51a.5.5 0 0 1-.707 0L12 1.707l-.646.647a.5.5 0 0 1-.708 0L10 1.707l-.646.647a.5.5 0 0 1-.708 0L8 1.707l-.646.647a.5.5 0 0 1-.708 0L6 1.707l-.646.647a.5.5 0 0 1-.708 0L4 1.707l-.646.647a.5.5 0 0 1-.708 0l-.509-.51z"/>
                                        <path fill-rule="evenodd" d="M3 4.5a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm8-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5z"/>
                                    </svg>
                                </div><!--//icon-holder-->

                            </div><!--//col-->
                            <div class="col-auto">
                                <h4 class="app-card-title">{{ $ps->tiket->label }}</h4>
                            </div><!--//col-->
                        </div><!--//row-->
                    </div><!--//app-card-header-->
                    <div class="app-card-body px-4">
                        <div class="row mb-4">
                            <div class="col-12">
                                <div class="item py-3">
                                    <div class="row justify-content-between align-items-center">
                                        <div class="col-auto">
                                            <div class="item-label"><strong> Tanggal Berangkat </strong></div>
                                            <div class="item-data">{{$ps->tanggal_berangkat}}</div>
                                        </div><!--//col-->
                                        <div class="col text-end">
                                            <div class="item-label"><strong> Tanggal_Pulang </strong></div>
                                            <div class="item-data">{{$ps->tanggal_pulang}}</div>
                                        </div><!--//col-->
                                    </div><!--//row-->
                                </div><!--//item-->
                            </div>
                        </div>
                        <div class="row g-4">
                            <div class="col-12 col-lg-4">
                                <img src="{{ asset("storage/" . $ps->qr_code) }}" width="250px" class="img-fluid">
                            </div>
                            <div class="col-12 col-lg-7">
                                <h5>Daftar Anggota Kelompok</h5>
                                @foreach($ps->pendaki as $pd)
                                    <div class="item border-bottom py-3">
                                        <div class="row justify-content-between align-items-center">
                                            <div class="col-auto">
                                                <div class="item-label"><strong>{{$pd->nama}} </strong></div>
                                                {{ $pd->pivot->status_pendaki }}

                                            </div><!--//col-->

                                        </div><!--//row-->
                                    </div><!--//item-->
                                @endforeach
                            </div>
                        </div>
                    </div><!--//app-card-body-->
                    <div class="app-card-footer p-4 mt-auto">
                    </div><!--//app-car
            d-footer-->
                </div><!--//app-card-->
                @if(isset($pemesananNotFound))
                    <div class="app-card alert alert-dismissible shadow-sm mb-4 border-left-decoration" role="alert">
                        <div class="inner">
                            <div class="app-card-body p-3 p-lg-4">
                                <div class="row gx-5 gy-3">
                                    <div class="col-12 col-lg-9">
                                        <div>{{ $pemesananNotFound }} </div>
                                    </div><!--//col-->
                                </div><!--//row-->
                            </div><!--//app-card-body-->

                        </div><!--//inner-->
                    </div><!--//app-card-->
                @endif
            </div><!--//col-->
        </div><!--//row-->
    @endforeach
@endsection

resources/views/pemesanan/tiket.blade.php
@extends('template.tempate-home')

@section('content')

<h1 class="app-page-title">Form Pendaftaran Pendakian</h1>
<hr class="mb-4">

@error('tanggalBerangkat')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror
@error('tanggalPulang')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror
@error('tiketId')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror

<div class="row g-4 settings-section">
    <div class="col-12 col-md-4">
        <h3 class="section-title">Jadwal Pendakian</h3>
        <div class="section-intro">isikan tanggal berangkat dan pulang untuk dapat memantau kegiatan pendaki</div>
    </div>
    <div class="col-12 col-md-8">
        <div class="app-card app-card-settings shadow-sm p-4">

            <div class="app-card-body">
                <form method="post" action="{{ route('pemesanan.post.tambah') }}">
                    @Csrf
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Tanggal Berangkat</label>
                        <input type="date" name="tanggalBerangkat" class="form-control" id="setting-input-1" value="<?= $_POST['tanggalBerangkat'] ?? '' ?>">
                    </div>
                    <div class="mb-3">
                        <label for="setting-input-2" class="form-label">Tanggal Pulang</label>
                        <input type="date" name="tanggalPulang" class="form-control" id="setting-input-2">
                    </div>
                    <div class="mb-3">
                        <label for="setting-input-2" class="form-label">Tiket</label>
                        <select class="form-select" name="tiketId" aria-label="Default select example">
                            @foreach($tikets as $tiket)
                            <option value="<?= $tiket->id ?>"><?= $tiket->label ?></option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn app-btn-primary">Submit</button>
                </form>
            </div>
            <!--//app-card-body-->

        </div>
        <!--//app-card-->
    </div>
</div>
<!--//row-->

@endsection