routes/web.php
<?php

use Illuminate\Support\Facades\Route;


// Home
Route::get("/", "HomeController@index")->name("index");
Route::get("/sop", "HomeController@sop")->name("sop");
Route::post("/sop", "HomeController@postSop")->name("post.sop");

// Home
Route::prefix("/home")->name("home.")->group(function (){
    Route::get("/dashboard","HomeController@dashboard")->name("dashboard")->middleware("mustLogin");
});

// admin
Route::prefix("/admin")->name("admin.")->group(function (){
    Route::get("/dashboard", "AdminController@dashboard")->name("dashboard");
    Route::get("/pemesanan", "AdminController@pemesanan")->name("pemesanan");
    Route::get("/tiket", "AdminController@tiket")->name("tiket");
    Route::get("/pendaki", "AdminController@pendaki")->name("pendaki");
    Route::get("/user", "AdminController@user")->name("user");
});

// Pemesanan Router
Route::prefix("/pemesanan")->name("pemesanan.")->group(function (){
    Route::get("/tambah", "PemesananController@tambah")->name("tambah");
    Route::post("/tambah","PemesananController@postTambah")->name("post.tambah");
    Route::get("/cetak-pdf/{pemesananId}", "PemesananController@cetakPdf")->name("cetakPdf");
    Route::get("/hapus/{pemesanan_pendaki}", "PemesananController@hapus")->name("hapus");
    Route::get("/riwayat", "PemesananController@riwayat")->name("riwayat");
    Route::get("/bayar/{id}", "PemesananController@bayar")->name("bayar")->middleware("mustLogin");
    Route::post("/bayar", "PemesananController@postBayar")->name("post.bayar")->middleware("mustLogin");
});

// User Router
Route::prefix("/user")->name("user.")->group(function (){
    Route::get("/login", "UserController@login")->name("login")->middleware("mustNotLogin");
    Route::post("/login", "UserController@postLogin")->name("post.login");
    Route::get("/registrasi/{pemesananId}", "UserController@formRegistrasi")->name("registrai");
    Route::post("/registrasi/{pemesananId}", "UserController@postRegistrasi")->name("post.registrasi");
    Route::get("/logout", "UserController@logout")->name("logout");
    Route::post("/add-admin", "UserController@addAdmin")->name("add.admin");
    Route::get("/register-account", "UserController@registerAccount")->name("register-account");
    Route::post("/register-account", "UserController@postRegisterAccount")->name("post.register-account");
});

// Pendaki Route
Route::prefix("/pendaki")->name("pendaki.")->group(function (){
    Route::post("/cek-nik", "PendakiController@cekNik")->name("cekNik");
    Route::get("/tambah-anggota/{pemesananId}", "PendakiController@tambahAnggota")->name("tambah.anggota");
    Route::post("/tambah-anggota/{pemesananId}", "PendakiController@postTambahAnggota")->name("post.tambah.anggota");
});

// Tiket
Route::prefix("/tiket")->name("tiket.")->group(function (){
    Route::post("/add", "TiketController@add")->name("add");
    Route::get("/delete/{id}", "TiketController@delete")->name("delete");
});

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Exceptions\PemesananNotFoundException;
use App\Exceptions\UserException;
use App\Http\Requests\AccountRegisterRequest;
use App\Http\Requests\AddUserAdminRequest;
use App\Http\Requests\UserLoginRequest;
use App\Http\Requests\UserRegistrasiPendakiRequest;
use App\Model\Pemesanan;
use App\Model\Session;
use App\Service\Impl\SessionServiceImpl;
use App\Service\Impl\UserServiceImpl;
use App\Service\SessionService;
use App\Service\UserService;
use Illuminate\Http\Request;

class UserController extends Controller
{
    private UserService $userService;
    private SessionService $sessionService;

    //
    public function __construct()
    {
        $this->userService = new UserServiceImpl();
        $this->sessionService = new SessionServiceImpl();
    }

    public function login()
    {
        return view("user/login", [
            "title" => "User Login"
        ]);
    }

    public function postLogin(UserLoginRequest $request)
    {

        try {
            $response = $this->userService->login($request);

            if ($response->user->role == "user"){
                $this->sessionService->create($response->user->id);
                return redirect()->route("home.dashboard");
            }else{
                $this->sessionService->create($response->user->id);
                return redirect()->route("admin.dashboard");
            }
        }catch (UserException $exception){
            return back()->with(["error" => $exception->getMessage()]);
        }

    }

    public function formRegistrasi($pemesanan){
        try {
            $response = $this->userService->formRegistrasiPendaki($pemesanan);
            return view("user/registrasi", [
               "pemesananId" => $response->pemesanan->id
            ]);
        }catch (PemesananNotFoundException $exception){
            return $exception->getMessage();
        }
    }

    public function postRegistrasi(UserRegistrasiPendakiRequest $request)
    {
        $response = $this->userService->registrasiPendaki($request);
        $this->sessionService->create($response->user->id);
        return redirect()->route("home.dashboard");
    }

    public function logout()
    {
        $this->sessionService->destroy();
        return redirect()->route("user.login");
    }

    public function addAdmin(AddUserAdminRequest $request)
    {
        $response = $this->userService->addUserAdmin($request);
        return back()->with("status", "Berhasil Menambah data Admin");
    }

    public function registerAccount()
    {
        return view("user.register-account", [
            "title" => "Registrasi User"
        ]);
    }
    public function postRegisterAccount(AccountRegisterRequest $request)
    {
        try {
            $response = $this->userService->accountRegister($request);
            return redirect()->route("user.login");
        }catch (UserException $exception){
            return back()->with(["error" => $exception->getMessage()]);
        }
    }
}

resources/views/user/login.blade.php
@extends("template.template-auth")

@section("content")


<div class="app-auth-branding mb-4"><a class="app-logo" href="index.html"><img class="logo-icon me-2" src="{{asset('assets/images/logo.png')}}" alt="logo"></a></div>
<h2 class="auth-heading text-center mb-5">Log in User</h2>

@if(isset($errors))
    @foreach($errors->all() as $message)
        <div class="alert alert-danger">
            {{ $message }}
        </div>
    @endforeach
@endif
@if(session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif

<div class="auth-form-container text-start">
    <form class="auth-form login-form" method="post" action="{{ route("user.post.login")  }}">
        {{ csrf_field() }}
        <div class="email mb-3">
            <label class="sr-only" for="signin-email">Username</label>
            <input id="signin-email" name="username" type="text" class="form-control signin-email" placeholder="Username">
        </div><!--//form-group-->
        <div class="password mb-3">
            <label class="sr-only" for="signin-password">Password</label>
            <input id="signin-password" name="password" type="password" class="form-control signin-password" placeholder="Password">
        </div><!--//form-group-->
        <div class="text-center">
            <button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto">Log In</button>
        </div>
    </form>

    <div class="auth-option text-center pt-5">Belum Punya Akun? Daftar <a class="text-link" href="{{ route('user.register-account') }}" >di sini</a>.</div>
</div><!--//auth-form-container-->



@endsection

resources/views/user/register-account.blade.php
@extends("template.template-auth")

@section("content")


    <div class="app-auth-branding mb-4"><a class="app-logo" href="index.html"><img class="logo-icon me-2" src="{{asset('assets/images/logo.png')}}" alt="logo"></a></div>
    <h2 class="auth-heading text-center mb-5">Log in User</h2>

    @if(isset($errors))
        @foreach($errors->all() as $message)
            <div class="alert alert-danger">
                {{ $message }}
            </div>
        @endforeach
    @endif
    @if(session('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
    @endif

    <div class="auth-form-container text-start">
        <form class="auth-form login-form" method="post" action="{{ route("user.post.register-account")  }}">
            {{ csrf_field() }}
            <div class="email mb-3">
                <label class="sr-only" for="signin-email">Nik</label>
                <input id="signin-email" name="nik" type="text" class="form-control signin-email" placeholder="Nik" value="{{ old("nik") }}">
            </div><!--//form-group-->
            <div class="email mb-3">
                <label class="sr-only" for="signin-email">Username</label>
                <input id="signin-email" name="username" type="text" class="form-control signin-email" placeholder="Username" value="{{ old("username") }}">
            </div><!--//form-group-->
            <div class="password mb-3">
                <label class="sr-only" for="signin-password">Password</label>
                <input id="signin-password" name="password" type="password" class="form-control signin-password" placeholder="Password">
            </div><!--//form-group-->
            <div class="text-center">
                <button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto">Daftar</button>
            </div>
        </form>

        <div class="auth-option text-center pt-5">Sudah Punya Akun? Login <a class="text-link" href="{{ route('user.login') }}" >di sini</a>.</div>
    </div><!--//auth-form-container-->



@endsection

resources/views/user/registrasi.blade.php
@extends("template.tempate-home")

@section("content")
<h1 class="app-page-title">Form Pendaftaran Pendakian</h1>
<hr class="mb-4">

@if(isset($errors))
@foreach($errors->all() as $message)
    <div class="alert alert-danger">
        {{ $message }}
    </div>
@endforeach
@endif

<form method="post" action="/user/registrasi/{{ $pemesananId }}">
    @Csrf
    <div class="row g-4 mt-1 settings-section">
        <div class="col-12 col-md-4">
            <h3 class="section-title">Data ketua Kelompok</h3>
            <div class="section-intro">isikan data lengkap anda untuk dapat melakukan pendaftan ketua kelompok</div>
        </div>
        <div class="col-12 col-md-8">
            <div class="app-card app-card-settings shadow-sm p-4">

                <div class="app-card-body">
                    <div class="mb-3">
                        <label for="setting-input-2" class="form-label">NIK</label>
                        <input type="text" name="nik" class="form-control" id="setting-input-2" value="{!! old('nik') !!}">
                    </div>
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Nama</label>
                        <input type="text" name="nama" class="form-control" id="setting-input-1" value="{!! old('nama') !!}">
                    </div>
                    <div class="mb-3">
                        <label for="setting-input-2" class="form-label">No Hp</label>
                        <input type="text" name="noHp" class="form-control" id="setting-input-2" value="{!! old('noHp') !!}">
                    </div>
                    <div class="mb-3">
                        <label for="setting-input-2" class="form-label">Tanggal Lahir</label>
                        <input type="date" name="tanggalLahir" class="form-control" id="setting-input-2" value="{!! old('tanggalLahir') !!}">
                    </div>
                    <div class="mb-3">
                        <label for="setting-input-2" class="form-label">Jenis Kelamin</label>
                        <select class="form-select" name="jenisKelamin" aria-label="Default select example">
                            <option value="L">Laki-laki</option>
                            <option value="P">Perempuan</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="setting-input-2" class="form-label">Alamat</label>
                        <input type="text" name="alamat" class="form-control" id="setting-input-2" value="{!! old('alamat') !!}">
                    </div>
                </div>
                <!--//app-card-body-->

            </div>
            <!--//app-card-->
        </div>
    </div>
    <div class="row g-4 mt-1 settings-section">
        <div class="col-12 col-md-4">
            <h3 class="section-title">Daftara User</h3>
            <div class="section-intro">Daftar user untuk dapar melanjutkan pendaftaran ketua</div>
        </div>
        <div class="col-12 col-md-8">
            <div class="app-card app-card-settings shadow-sm p-4">

                <div class="app-card-body">
                    <div class="mb-3">
                        <label for="setting-input-2" class="form-label">Username</label>
                        <input type="text" name="username" class="form-control" id="setting-input-2" value="{!! old('username') !!}">
                    </div>
                    <div class="mb-3">
                        <label for="setting-input-1" class="form-label">Password</label>
                        <input type="password" name="password" class="form-control" id="setting-input-1" value="{!! old('password') !!}">
                    </div>

                    <button type="submit" class="btn app-btn-primary">Daftar</button>
                </div>
                <!--//app-card-body-->

            </div>
            <!--//app-card-->
        </div>
    </div>
</form>
@endsection